-- Create notifications table
create table public.notifications (
    id bigint generated by default as identity primary key,
    player_id uuid references public.players(id) on delete cascade not null,
    type text check (type in ('attack', 'income', 'job', 'family', 'system', 'market')) not null,
    title text not null,
    message text not null,
    read boolean default false,
    created_at timestamptz default now()
);

-- Enable RLS
alter table public.notifications enable row level security;

-- Policies
create policy "Users can view their own notifications"
    on public.notifications for select
    using ( auth.uid() = player_id );

create policy "Users can update their own notifications (mark as read)"
    on public.notifications for update
    using ( auth.uid() = player_id );

-- Create index for performance
create index notifications_player_id_idx on public.notifications(player_id);
create index notifications_created_at_idx on public.notifications(created_at);
